import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class BunkoMeterPage {
    private JTextField totalAttendence;
    private JTextField presentClasses;
    private JTextField absentClasses;
    private JButton calculateAttendence;
    private JPanel bunkoMeterPanel;
    private JButton backButton;

    private JFrame frame;

    public BunkoMeterPage(JFrame frame) {
        this.frame = frame;

        initComponents();

        calculateAttendence.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Add your logic to calculate attendance here
            }
        });

        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Switch back to the main menu
                frame.setContentPane(new mainMenu(frame).mainMenuPanel);
                frame.revalidate(); // Refresh the frame
                frame.pack(); // Adjust the frame size to fit the content
            }
        });
    }

    private void initComponents() {
        // Initialize your components here if not generated by a GUI designer
    }

    public JPanel getBunkoMeterPanel() {
        return bunkoMeterPanel;
    }

    // Main function
    public static void main(String[] args) {
        JFrame frame = new JFrame("BunkoMeter");
        frame.setContentPane(new BunkoMeterPage(frame).bunkoMeterPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
