import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class orderDelivery {
    private JPanel orderDeliveryPane;
    private JTextField RecieverName;
    private JTextField DeliveryPartner;
    private JTextField OTP;
    private JButton confirmButton;

    public orderDelivery(JFrame frame) {
        // Initialize components and set up the panel
        initComponents(); // Replace with actual initialization method if necessary

        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(orderDeliveryPane, "Your order has been verified! You can now go and collect the order.", "Order Verified", JOptionPane.INFORMATION_MESSAGE);
            }
        });
    }

    private void initComponents() {
        // Initialize components here, if not generated by the form designer
    }

    public JPanel getOrderDeliveryPane() {
        return orderDeliveryPane;
    }

    public static void main(String[] args) {
        // Create a JFrame to hold the orderDelivery panel
        JFrame frame = new JFrame("Order Delivery");
        frame.setTitle("Order Delivery");
        frame.setSize(450, 800);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Create an instance of orderDelivery and set it as the content pane
        orderDelivery panel = new orderDelivery(frame);
        frame.setContentPane(panel.getOrderDeliveryPane());

        // Display the frame
        frame.setLocationRelativeTo(null); // Center the frame on the screen
        frame.setVisible(true);
    }
}
