import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class orderDelivery {
    private JPanel orderDeliveryPane;
    private JTextField RecieverName;
    private JTextField DeliveryPartner;
    private JTextField OTP;
    private JButton confirmButton;
    private JButton backButton;

    private JFrame frame; // Reference to the shared JFrame

    public orderDelivery(JFrame frame) {
        this.frame = frame; // Store the frame reference

        // Initialize components and set up listeners
        initComponents();

        confirmButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String recieverName = RecieverName.getText();
                String deliveryPartner = DeliveryPartner.getText();
                String oTP = OTP.getText();

                if (recieverName.equals("lakshya") && deliveryPartner.equals("Blue Dart") && oTP.equals("4669")){
                    JOptionPane.showMessageDialog(orderDeliveryPane,
                            "Your order has been verified! You can now go and collect the order.",
                            "Order Verified", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(orderDeliveryPane,
                            "No such order found!! Please contact the delivery partner.",
                            "Wrong Input", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        // Back button listener to return to the main menu
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Switch back to the main menu
                frame.setContentPane(new mainMenu(frame).mainMenuPanel);
                frame.revalidate(); // Refresh the frame
                frame.pack(); // Adjust the frame size to fit the content
            }
        });
    }

    private void initComponents() {
        // Initialize your components here if not generated by a GUI designer
    }

    public JPanel getOrderDeliveryPane() {
        return orderDeliveryPane;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("Order Delivery");
        frame.setTitle("Order Delivery");
        frame.setSize(450, 800);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // Set the order delivery panel as the content pane
        frame.setContentPane(new orderDelivery(frame).getOrderDeliveryPane());

        frame.setLocationRelativeTo(null); // Center the frame on the screen
        frame.setVisible(true);
    }
}
